### PR TITLE
Split index.js file into smaller files

### PR DESCRIPTION
**Pull request by calebmchenry**
td.replace is the `testdouble` function for mocking a module.
Added `eslint-disable-next-line` due to needing to require
a module dynamically in the test since that is how the module
mocking works

### CODE REVIEW

**Comment by calebmchenry** [comment]
#18

**Comment by calebmchenry** [comment]
Happy to reorganize if you had a different structure in mind

**Comment by artlogic** [comment]
@calebmchenry reviewing this - thanks for your patience and contribution!

**Comment by artlogic** [comment]
@calebmchenry I'm hoping to merge #29 before this one, but if that stretches on too long I'll go ahead and merge this. Thanks for your patience.

**Comment by artlogic** [comment]
@calebmchenry thanks for your patience. I'm in the process of fixing a few odds and end from adding the babel support - but if you could go ahead and start fixing the conflicts, we can get this merged pretty quick. Thanks!

**Comment by calebmchenry** [comment]
From a quick attempt it seems to be non trivial conflicts. I will try to get to it when I can.

**Comment by artlogic** [comment]
@calebmchenry I'm sorry I haven't gotten to this yet, but I will. Do you mind if I re-open?

**Comment by calebmchenry** [comment]
@artlogic Sure thing. I was cleaning up my repos so I had already the repo. Not sure I can reopen this PR but here is a new one #67

**Pull request closed without merging**
